### ISSUE TITLE
https2http

### ISSUE THREAD

**Issue by matbgn** [haade-administrator/haade-addons#15]
How do you configure a https2http config ?

Or how to manage https connection with your addon ? Do you have an exemple working ?

**Comment by haade-administrator** [comment]
Sorry i haven't look your messages, have you need help ?

**Comment by matbgn** [comment]
Noop thank you I abandoned FRP solution completly to use solution due to my HA limitation

**Comment by haade-administrator** [comment]
you can use my server if you whant access is free, ssl and tunnelised
